### ISSUE TITLE
error building go-oauth2 redis

### ISSUE THREAD

**Issue by cosma** [go-oauth2/redis#7]
Since today   I get the following error when building the library in docker on top of 
`golang:1.12.5-alpine` image.

`/go/src/gopkg.in/go-oauth2/redis.v3/options.go:78:3: cannot use o.Dialer (type func() (net.Conn, error)) as type func(string, string) (net.Conn, error) in field value`

I tried to debug it but i didn't figure it out yet what is causing the error.
Strange is that previous days it was working to build the library
Do you have any idea why?
Quick help will be much appreciated.
Thank you and have a good day!

UPDATE: actually looks like is caused because of this https://github.com/go-redis/redis/commit/3da4357c0cc5d528b3ef49307f7a34db40eaba0e

**Comment by LyricTian** [comment]
Already fixed, sorry, some busy recently.

**Comment by cosma** [comment]
Thanks @LyricTian . Is highly  appreciated.
